name: 'Help Kids '
favicon: null
layout_spectrum: 0.75328
typography_spectrum: 0.7068518253508955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77729791-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5d5d5'
    - '#9e9e9e'
    - '#595959'
    - '#f8f8f8'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
